service: tees-uni-internship-project-python-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app 
    pythonBin: python3
  pythonRequirements:
    pythonBin: /usr/bin/python3

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements